config/routes.rb
Blojkungen::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get 'cart/checkout' => 'cart#checkout'
  resources :home, :user, :product, :cart, :categorie
  devise_for :users

  # Add new logout path
  devise_for :users do
    get 'logout' => 'devise/sessions#destroy'
  end



  #match '/add', :to => 'product#add_to_cart'
  # first created -> highest priority.

  # Sample of regular route:
  match  "cart/:action", :controller => 'cart', :action => "add"
  #match  "cart/:action", :controller => 'cart', :action => "remove"
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items
  has_many :products, through: :cart_items
  def add(product_id, shopper_id, qty=1)
    item    = cart_items.find_by_cart_id_and_product_id(shopper_id, product_id)
    product = Product.find(product_id)

    if item.nil?
      ci = cart_items.create(product_id: product_id,
                             amount:     qty,
                             cart_id:    shopper_id,
                             price:      product.price)
    else  
      c = CartItem.find(item.id)
      c.amount = qty.to_i
      c.save
    end
  end
  def remove(product_id)
    ci = cart_items.find_by_id(product_id)

    if ci.amount > 1  
      ci.update_attribute(:amount, ci.amount - 1)
    else 
      CartItem.destroy(ci.id)
    end
    return ci
  end

  def total
    cart_items.inject(0) {|sum, n| n.price * n.amount + sum}
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product 
  def total
    cart.inject(0) {|sum, n| n.price * n.amount + sum}
  end
end

app/models/categorie.rb
class Categorie < ActiveRecord::Base
  has_many :products
   def to_s
    categorie_name
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :cart_items
  has_many :carts, through: :cart_items
  belongs_to :categorie
  def add(product_id, shopper_id, qty)
    items = cart_items.find_all_by_cart_id(shopper_id)
    product = Product.find(product_id)

    if items.size < 1
      ci = cart_items.create(product_id: product_id,
                             amount:     1,
                             cart_id:    shopper_id,
                             price:      product.price)
    else
      ci = items.first
      if qty.nil?
        ci.update_attribute(:amount, ci.amount + 1)
      else 
        ci.update_attribute(:amount, qty) 
      end
    end
    ci
  end
  def remove(product_id)
    ci = cart_items.find_by_id(product_id)

    if ci.amount > 1  
      ci.update_attribute(:amount, ci.amount - 1)
    else 
      CartItem.destroy(ci.id)
    end
    return ci
  end

  def total
    cart_items.inject(0) {|sum, n| n.price * n.amount + sum}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :f_adress, :f_postnumber, :f_county, :l_adress, :l_postnumber, :l_county, :name, :aftername, :phone
  validates_presence_of :email, :password, :f_adress, :f_postnumber, :f_county, :l_adress, :l_postnumber, :l_county, :name, :aftername, :phone, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :init_cart
  def init_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
   def index
      @in_cart = CartItem.find_all_by_cart_id(session[:cart_id], include: [:product])
   end
   def checkout
    if user_signed_in?
      #Magic here
      @in_cart = CartItem.find_all_by_cart_id(session[:cart_id], include: [:product])
      @user    = User.find(current_user.id)
    else 
      redirect_to :controller => "user"
    end
      
   end
   def add
    #@product = Product.find(params[:id])
    if request.post?
      @item = @cart.add(params[:id], session[:cart_id], params[:qty])
      #flash[:cart_notice] = "Added <em>#{@item.product.name}</em>" 
      redirect_to :controller => "cart"
    else
     # render
    end
  end
  def remove
    #@product = Product.find(params[:id])
    if request.xhr?
      @item = @cart.remove(params[:id])
      flash.now[:cart_notice] = "Removed 1 <em>#{@item.product.name}</em>"
      render :action => "remove_with_ajax" 
    elsif request.post?
     @item = @cart.remove(params[:id])
      flash[:cart_notice] = "Removed 1 <em>#{@item.product.name}</em>" 
      redirect_to :controller => "cart"
    else
      #render
    end
  end
end

app/controllers/categorie_controller.rb
class CategorieController < ApplicationController
  def index
    @categories = Categorie.find(:all)
  end
  def show
    @category = Categorie.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  def index
    @product = Product.find(:all)
  end

  def show
     @product = Product.find(params[:id])
  end

  def remove
    @cart = CartItem.find(params[:id])
    if request.xhr?
      @item = @cart.remove(params[:id])
      flash.now[:cart_notice] = "Removed 1 <em>#{@item.product.name}</em>"
      render :action => "remove_with_ajax" 
    elsif request.post?
      @item = @cart.remove(params[:id])
      flash[:cart_notice] = "Removed 1 <em>#{@item.product.name}</em>" 
      redirect_to :controller => "cart"
    else
      #render
    end
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!
  def update
      @user = User.find(params[:id])
      if @user.update_attributes(params[:user])
         redirect_to action: 'checkout', controller: 'cart'
      else
       
      end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
  def total_sum(object)
    object.inject(0) {|sum, n| n.price * n.amount + sum}
  end
  def total_products(object)
    object.size
  end
end

app/helpers/categorie_helper.rb
module CategorieHelper
end

app/views/cart/add.html.erb
add.html.erb

app/views/cart/checkout.html.erb
<%= form_for @user do |f| %>
	<h1>Dina uppgifter</h1>
	<h3>Personliga uppgifter</h3>
	<%= f.label "Förnamn" %>:
	<%= f.text_field :name %><br />
	<%= f.label "Efternamn" %>:
	<%= f.text_field :aftername %><br />
	<%= f.label "Telefon" %>:
	<%= f.text_field :phone %>

	<h3>Fakturaadress</h3>
	<%= f.label "Adress" %>:
	<%= f.text_field :f_adress %><br/>
	<%= f.label "Postnummer" %>:
	<%= f.text_field :f_postnumber %><br/>
	<%= f.label "Ort" %>:
	<%= f.text_field :f_county %><br/><br/>
	<%= f.label "Använda faktura adress till leveransadress" %> 
	<%= check_box_tag(:copy_adress) %>
	<h3>Leveransuppgifter</h3>
	<%= f.label "Adress" %>:
	<%= f.text_field :l_adress %><br/>
	<%= f.label "Postnummer" %>:
	<%= f.text_field :l_postnumber %><br/>
	<%= f.label "Ort" %>:
	<%= f.text_field :l_county %><br/>
	<%= f.submit %>
<% end %>
<%= link_to "Bekräfta köp", "/cart/checkout" %>

app/views/cart/index.html.erb
<h2>Kundkorg <%= @total %></h2>

<% if @in_cart.empty? %>
	<p>Din kundkorg är tom</p>
	<% else %> 
	<% @in_cart.each do |c| %>
		<big><%= c.product.name %></big>
		<p><%= c.product.description %></p>
		<p><%= c.product.price %> kr</p>
		<%= form_tag("/cart/add", :method => "post") do %>
			<%= text_field_tag(:qty, c.amount) %>
			<%= hidden_field_tag(:id, c.product.id) %>
			<%= submit_tag("Uppdatera") %>
		<% end %>
		<p>Antal: <%= c.amount %></p>
		<%= button_to "Ta bort", controller: 'cart', :action => "remove", :id => c.id %>
		
		<p>---------------------------</p>
	<% end %>

	<p>Antal Produkter: <%= total_products(@in_cart) %>
	<p>Summa: <%= total_sum(@in_cart) %> kr</p>
	<%= link_to "Kassa", "/cart/checkout" %>
<% end %>

app/views/cart/remove.html.erb
<%= debug @product %>

app/views/categorie/index.html.erb
<b>Undermeny: </b>
<% @categories.each do |categorie| %>
	<%= link_to categorie.categorie_name, categorie_path(categorie) %>
<% end %>

app/views/categorie/show.html.erb
<% if @category.products.empty? %>
	<p>Finns inga artiklar i denna kategorien.
<% else %>
	<% @category.products.each do |product| %>
		<%= link_to product.name, product_path(product) %>	
	<% end %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blojkungen</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "grid" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper" class="row">
		<div class="column grid_12">
			<ul id="main_navigation">
				<% if user_signed_in? %>
					<li>Inloggad som: <%= current_user.email %></li>
					<li><%= link_to "Logga ut", logout_path %></li>
				<% else %>
					<li><%= link_to "Logga in", user_session_path %></li>
				<% end %>

				<li><%= link_to "Kundvag", cart_index_path %></li>
				<li><%= link_to "Sortiment", categorie_index_path %></li>
			<ul>
		</div>
		<div id="yield_content" class="column grid_12" data-pjax-container>
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/product/index.html.erb
<h1>Sortiment</h1>
<% @product.each do |p| %>
  <p>Namn: <%= p.name %></p>
  <p>Sku: <%= p.sku %></p>
  <p>Beskrivning: <%= p.description %></p>
  <p>Pris: <%= p.price %> kr</p>
  <%= link_to "Visa produkt", product_path(p.id) %>
<% end %>

app/views/product/show.html.erb
<h3><%= @product.name %></h3>
<p><%= @product.sku %></p>
<p><%= @product.price %> kr</p>
<p><%= @product.weight %></p>
<%= form_tag("/cart/add", :method => "post") do %>
			<%= text_field_tag(:qty, 1, style: "width: 20px;") %>
			<%= hidden_field_tag(:id, @product.id) %>
			<%= submit_tag("Köp") %>
<% end %>

app/views/user/update.html.erb
update.html.erb